name: Scheduled Energy Price Check

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread oauth2client google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Write Service Account to File
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo "$SERVICE_ACCOUNT_JSON" > creds.json

      - name: Run script
        run: python google.py

      - name: Clean up Service Account File
        run: rm creds.json
